version: "3.8"

services:
    backend-server:
        container_name: backend-server
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 443:443
            - 80:80
        volumes:
            - .:/app
            - /app/obj/ # <- directory won't be mounted
            - /app/bin/ # <- directory won't be mounted
            - ${HOME}/.aspnet/https:/https # Directory with the certificate for the https connection
            # - backend_volume:/root/.aspnet/DataProtection-Keys
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_URLS: https://*:443;http://*:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: "Eketa2024!"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/CerthBackend.pfx"
            ASPNETCORE_HTTPS_PORT: "443" # Defines the port where we will receive HTTPS requests
            ASPNETCORE_HTTP_PORT: "80" # Defines the port where we will receive HTTP requests
